# Generated by Django 3.2.8 on 2021-10-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_activities', '0006_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
